server:
  port: 10020
spring:
  application:
    name: microservice-consumer-movie-ribbon
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
  instance:
    preferIpAddress: true