server:
  port: 10031
spring:
  application:
    name: microservice-consumer-movie-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
  instance:
    preferIpAddress: true


feign:
  hystrix:
    enabled: true

